
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 17 02:08:52 UYT 2015
//----------------------------------------------------

package com.pyjava.parser;

/** CUP generated class containing symbol constants. */
public class sym1 {
  /* terminals */
  public static final int AS = 5;
  public static final int SHIFTL = 63;
  public static final int FROM = 3;
  public static final int LCURLY = 51;
  public static final int TYPE = 29;
  public static final int NEWLINE = 31;
  public static final int RAISE = 20;
  public static final int EXP = 56;
  public static final int LAMBDA = 27;
  public static final int NAME = 35;
  public static final int PASS = 12;
  public static final int INDENT = 74;
  public static final int DIVE = 57;
  public static final int XORB = 61;
  public static final int DEDENT = 75;
  public static final int ELIF = 6;
  public static final int RPAREN = 46;
  public static final int INTEGER = 37;
  public static final int LPAREN = 47;
  public static final int DEL = 2;
  public static final int YIELD = 13;
  public static final int FALSE = 78;
  public static final int NOT = 67;
  public static final int DEF = 25;
  public static final int FLOAT = 39;
  public static final int MAJOREQ = 73;
  public static final int MOD = 58;
  public static final int CLASS = 17;
  public static final int EXCEPT = 15;
  public static final int COMA = 42;
  public static final int TRUE = 77;
  public static final int TAB = 33;
  public static final int LONG = 38;
  public static final int PLUS = 52;
  public static final int EXEC = 18;
  public static final int WHILE = 4;
  public static final int ASSIGN = 36;
  public static final int STRING3 = 41;
  public static final int NONE = 76;
  public static final int FOR = 26;
  public static final int DIV = 55;
  public static final int RETURN = 24;
  public static final int MULT = 54;
  public static final int NOTB = 62;
  public static final int ELSE = 10;
  public static final int TRY = 28;
  public static final int BREAK = 14;
  public static final int DOT = 43;
  public static final int MAJOR = 71;
  public static final int EOF = 0;
  public static final int SEMICOLON = 45;
  public static final int COMMENT = 34;
  public static final int PRINT = 30;
  public static final int MINOR = 70;
  public static final int IMPORT = 16;
  public static final int IS = 23;
  public static final int MINUS = 53;
  public static final int IN = 19;
  public static final int OR = 66;
  public static final int error = 1;
  public static final int DIFF = 69;
  public static final int FINALLY = 22;
  public static final int WHITESPACE = 32;
  public static final int CONTINUE = 21;
  public static final int IF = 11;
  public static final int COLON = 44;
  public static final int ASSERT = 9;
  public static final int RBRACKET = 48;
  public static final int ORB = 60;
  public static final int MINOREQ = 72;
  public static final int ANDB = 59;
  public static final int GLOBAL = 7;
  public static final int STRING = 40;
  public static final int AND = 65;
  public static final int LBRACKET = 49;
  public static final int WITH = 8;
  public static final int RCURLY = 50;
  public static final int EQUALS = 68;
  public static final int SHIFTR = 64;
}

