
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 29 23:53:20 UYT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym1 {
  /* terminals */
  public static final int AS = 15;
  public static final int SHIFTL = 61;
  public static final int FROM = 13;
  public static final int LCURLY = 11;
  public static final int NEWLINE = 39;
  public static final int RAISE = 30;
  public static final int EXP = 54;
  public static final int LAMBDA = 37;
  public static final int NAME = 43;
  public static final int PASS = 22;
  public static final int DIVE = 55;
  public static final int XORB = 59;
  public static final int ELIF = 16;
  public static final int RPAREN = 6;
  public static final int INTEGER = 45;
  public static final int LPAREN = 7;
  public static final int DEL = 12;
  public static final int YIELD = 23;
  public static final int NOT = 65;
  public static final int DEF = 35;
  public static final int FLOAT = 47;
  public static final int MAJOREQ = 71;
  public static final int MOD = 56;
  public static final int CLASS = 27;
  public static final int EXCEPT = 25;
  public static final int COMA = 2;
  public static final int LONG = 46;
  public static final int PLUS = 50;
  public static final int EXEC = 28;
  public static final int WHILE = 14;
  public static final int ASSIGN = 44;
  public static final int STRING3 = 49;
  public static final int FOR = 36;
  public static final int DIV = 53;
  public static final int RETURN = 34;
  public static final int MULT = 52;
  public static final int NOTB = 60;
  public static final int ELSE = 20;
  public static final int TRY = 38;
  public static final int BREAK = 24;
  public static final int DOT = 3;
  public static final int MAJOR = 69;
  public static final int EOF = 0;
  public static final int SEMICOLON = 5;
  public static final int COMMENT = 42;
  public static final int MINOR = 68;
  public static final int IMPORT = 26;
  public static final int IS = 33;
  public static final int MINUS = 51;
  public static final int IN = 29;
  public static final int OR = 64;
  public static final int error = 1;
  public static final int DIFF = 67;
  public static final int FINALLY = 32;
  public static final int WHITESPACE = 40;
  public static final int CONTINUE = 31;
  public static final int IF = 21;
  public static final int COLON = 4;
  public static final int ASSERT = 19;
  public static final int RBRACKET = 8;
  public static final int INPUTCHARACTER = 41;
  public static final int ORB = 58;
  public static final int ANDB = 57;
  public static final int MINOREQ = 70;
  public static final int GLOBAL = 17;
  public static final int STRING = 48;
  public static final int AND = 63;
  public static final int LBRACKET = 9;
  public static final int WITH = 18;
  public static final int RCURLY = 10;
  public static final int EQUALS = 66;
  public static final int SHIFTR = 62;
}

